# Generated by Django 5.0.3 on 2024-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literaryLoans_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.SmallIntegerField()),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.SmallIntegerField()),
                ('title', models.CharField(default='', max_length=255)),
                ('status', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lender_id', models.SmallIntegerField()),
                ('quantity', models.IntegerField()),
                ('author_id', models.SmallIntegerField()),
                ('available', models.BooleanField()),
                ('book_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_book_rating', models.IntegerField()),
                ('condition_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_condition_rating', models.IntegerField()),
                ('image', models.ImageField(upload_to='book_images/')),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.SmallIntegerField()),
                ('genre_id', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.SmallIntegerField()),
                ('borrower_id', models.SmallIntegerField()),
                ('book_id', models.SmallIntegerField()),
                ('status', models.SmallIntegerField()),
                ('quantity', models.IntegerField()),
                ('request_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.SmallIntegerField()),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='', max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Rented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_id', models.SmallIntegerField()),
                ('borrower_id', models.SmallIntegerField()),
                ('book_id', models.SmallIntegerField()),
                ('quantity', models.IntegerField()),
                ('rent_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.SmallIntegerField()),
                ('borrower_id', models.SmallIntegerField()),
                ('book_id', models.SmallIntegerField()),
                ('status', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('request_date', models.DateField()),
            ],
        ),
    ]
