# Generated by Django 4.2.11 on 2024-03-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literaryLoans_app', '0002_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='rented',
            name='rent_id',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='request_id',
        ),
    ]
