# Generated by Django 4.2.11 on 2024-03-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literaryLoans_app', '0003_remove_book_book_id_remove_borrowrequest_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
