# Generated by Django 4.2.11 on 2024-03-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literaryLoans_app', '0004_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='rented_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rented', to='literaryLoans_app.rented'),
        ),
    ]
